# README updater workflow

name: README Updater

on:
  # Run every night at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  readme-updater:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run updater script
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/updater.py

      - name: Check for changes
        run: |
          git diff --quiet || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.changes_detected == 'true'
        run: |
          git config --global user.name "thelicato"
          git config --global user.email "thelicato@users.noreply.github.com"
          git add README.md
          git commit -m "cicd: automatic compatibility matrix update ($(date -u +'%Y-%m-%d'))"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
